import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'am' | 'or';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.dashboard': 'Dashboard',
    'nav.trackOrder': 'Track Order',
    'header.language': 'Select language',
    'header.organic': 'Organic',
    'common.welcome': 'Welcome',
    'common.logout': 'Logout',
    'common.currency': 'ETB',
    'common.submit': 'Submit Request',
    'common.loading': 'Processing...',
    'common.sending': 'Sending...',
    
    // Hero Section
    'hero.title1': "Nature's Purity,",
    'hero.title2': "Packaged for You.",
    'hero.subtitle': "Premium organic supplements, ethically sourced from Ethiopian farms and delivered with care.",
    'hero.btn.order': "Place an Order",
    'hero.btn.about': "About Us",
    'hero.btn.bulk': "Bulk Orders",
    'hero.stat.products': "Products",
    'hero.stat.customers': "Customers",
    'hero.stat.natural': "Natural",
    'hero.stat.farms': "Local Farms",

    // Best Sellers
    'bestSellers.title': 'Featured Organic',
    'bestSellers.titleHighlight': 'Supplements',
    'bestSellers.subtitle': 'Sourced from Ethiopian highlands. Every product is third-party tested and certified organic.',
    'bestSellers.badgeFeatured': 'Featured',
    'bestSellers.comingSoon': 'Coming Soon',
    'bestSellers.comingSoonDesc': 'Our product catalog is being updated. Check back shortly.',
    'bestSellers.priceFrom': 'Price From',
    'bestSellers.defaultDesc': 'Premium organic supplement sourced from the Ethiopian highlands.',
    'bestSellers.buyNow': 'Buy Now',
    'bestSellers.orderAny': 'Order Any Product',

    // Daily Highlights
    'dailyHighlights.shopByCategory': 'Shop By Category',
    'dailyHighlights.defaultDesc': 'Experience the pure, natural benefits of this authentic product. Harvested and prepared with care.',

    // Categories
    'categories.powders': 'Powders',
    'categories.oils': 'Oils',
    'categories.seeds': 'Seeds',
    'categories.supplements': 'Supplements',
    'categories.herbsSpices': 'Herbs & Spices',
    'categories.essentialOils': 'Essential Oils',
    'categories.naturalBeauty': 'Natural Beauty',
    'categories.wellness': 'Wellness',

    // Tags
    'tags.trending': 'Trending',
    'tags.bestseller': 'Bestseller',
    'tags.organic': 'Organic',
    'tags.supplement': 'Supplement',
    'tags.pure': 'Pure',
    'tags.superfood': 'Superfood',
    'tags.essential': 'Essential',
    'tags.herbal': 'Herbal',
    'tags.aromatic': 'Aromatic',
    'tags.natural': 'Natural',
    'tags.spice': 'Spice',

    // Carousel
    'carousel.subtitle': 'Learn While Visiting Us',
    'carousel.title': 'Build Your Healthy Self',
    'carousel.desc': 'Click the cards to explore different natural benefits of our authentic Ethiopian harvest.',
    'carousel.shopNow': 'Shop now',

    // Story
    'story.title': 'Rooted in Heritage,',
    'story.titleHighlight': 'Driven by Purity.',
    'story.desc': 'Founded in the fertile valleys of Asella, our enterprise began with a simple mission: to preserve the ancient agricultural wisdom of Ethiopia while meeting international organic standards. We believe that true health comes from the earth, untouched and honored.',
    'story.feature1Title': '100% Organic',
    'story.feature1Desc': 'Every product is certified to be free from synthetic additives.',
    'story.feature2Title': 'Ethically Sourced',
    'story.feature2Desc': 'We support our community by providing fair wages and sustainable practices.',
    'story.feature3Title': 'Quality Tested and approved by ECAE and AAFDA',
    'story.feature3Desc': 'Rigorous laboratory testing for purity and potency in every batch.',
    'story.feature4Title': 'Heritage & Tradition',
    'story.feature4Desc': 'Combining generational agricultural knowledge with modern scientific refinement.',

    // Reviews
    'reviews.subtitle': 'Real Experiences',
    'reviews.title': 'Voices of Our ',
    'reviews.titleHighlight': 'Community',
    'reviews.moreVideos': 'More Videos',

    // Contact
    'contact.subtitle': 'Get In Touch',
    'contact.title': 'Connect With Our ',
    'contact.titleHighlight': 'Heritage',
    'contact.desc': 'Whether you\'re looking to visit our facilities, inquire about our sustainable practices, or arrange a meeting with our team, we welcome your connection to our heritage.',
    'contact.supportTitle': 'Customer Support',
    'contact.amharicSupport': 'Amharic Support',
    'contact.oromooSupport': 'Afaan Oromoo Support',
    'contact.storePiasaTitle': 'Piasa Store',
    'contact.storePiasaDesc': 'Addis Ababa, Piazza Giorgis, Ethel Appartment',
    'contact.directions': 'Directions',
    'contact.officeTitle': 'Main Office',
    'contact.officeDesc': 'Jemo Mickael Woreda 03,Africa Building, Addis Ababa, Ethiopia',
    'contact.visitUs': 'Visit us',
    'contact.formTitle': 'Place an Appointment',
    'contact.formSuccess': 'Request sent successfully! We will contact you soon.',
    'contact.formError': 'Failed to send request. Please try again.',
    'contact.fullName': 'Full Name *',
    'contact.fullNamePlaceholder': 'Enter your name',
    'contact.phone': 'Phone Number *',
    'contact.phonePlaceholder': 'Enter your phone number',
    'contact.email': 'Email Address (Optional)',
    'contact.emailPlaceholder': 'Enter your email',
    'contact.date': 'Preferred Date *',

    // Footer
    'footer.paymentOptions': 'Payment Options',
    'footer.importantLinks': 'Important Links',
    'footer.home': 'Home',
    'footer.catalog': 'Catalog',
    'footer.ourStory': 'Our Story',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.followUs': 'Follow Us',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2026 Asella Organic Enterprise. All rights reserved.',
    'footer.rights': '© 2026 Asella Organic Enterprise. All rights reserved.',
    'footer.termsOfService': 'Terms of Service',

    // OrderForm
    'orderForm.titleFranchise': 'Franchise Partner Portal',
    'orderForm.titleSales': 'New Sales Order',
    'orderForm.titleDefault': 'Complete Your Order',
    'orderForm.subtitleFranchise': 'Place bulk/wholesale requests for franchise stores.',
    'orderForm.subtitleSales': 'Establish a new retail client entry.',
    'orderForm.ordering': 'Ordering: ',
    'orderForm.customerName': 'Customer / Entity Name',
    'orderForm.customerNamePlaceholder': 'Full name or company name',
    'orderForm.franchiseType': 'Franchise Type',
    'orderForm.gender': 'Gender',
    'orderForm.select': 'Select',
    'orderForm.male': 'Male',
    'orderForm.female': 'Female',
    'orderForm.ageGroup': 'Age Group',
    'orderForm.source': 'Source',
    'orderForm.sourceWebsite': 'Website / Online',
    'orderForm.sourcePhone': 'Phone',
    'orderForm.sourceWalkIn': 'Walk-in',
    'orderForm.sourceOther': 'Other',
    'orderForm.orderType': 'Order Type',
    'orderForm.delivery': 'Delivery',
    'orderForm.pickup': 'Pickup',
    'orderForm.referralCode': 'Referral Code (Optional)',
    'orderForm.location': 'Location',
    'orderForm.locAddis': 'Addis Ababa',
    'orderForm.locOther': 'Other Regions',
    'orderForm.locAbroad': 'Abroad',
    'orderForm.city': 'City / Specific Area',
    'orderForm.phone': 'Phone Number',
    'orderForm.itemDetailsTitle': 'Item Details',
    'orderForm.itemLabel': 'Item',
    'orderForm.itemPlaceholder': 'Select item...',
    'orderForm.packageSize': 'Package Size',
    'orderForm.chooseItemFirst': 'Choose item first',
    'orderForm.qty': 'Qty',
    'orderForm.deliveryDate': 'Delivery Date',
    'orderForm.addAnotherItem': '+ Add Another Item',
    'orderForm.deliveryFeeInfoTitle': 'Delivery Fee Information:',
    'orderForm.deliveryFeeInfoText': 'Addis Ababa: 200 ETB | Outside Addis Ababa: 300 ETB | International: Based on region',
    'orderForm.notes': 'Order Notes / Special Instructions',
    'orderForm.attachment': 'Attachment (Receipt / ID)',
    'orderForm.total': 'Total:',
    'orderForm.successMessage': 'Order submitted successfully!',
    'orderForm.errorMessage': 'Failed to submit order',
    'orderForm.errorOccurred': 'An error occurred',

    // Tracking
    'tracking.subtitle': 'Order Tracking',
    'tracking.title': 'Track Your Order',
    'tracking.desc': 'Enter your Order ID below to get real-time status updates on your package.',
    'tracking.placeholder': 'e.g. ORD-001234',
    'tracking.searching': 'Searching...',
    'tracking.trackBtn': 'Track',
    'tracking.notFound': 'No order was found for that ID. Check the order number and try again.',
    'tracking.errorMsg': 'Unable to track this order',
    'tracking.orderIdLabel': 'Order ID',
    'tracking.placedOnLabel': 'Placed On',
    'tracking.customerLabel': 'Customer',
    'tracking.totalAmountLabel': 'Total Amount',
    'tracking.statusLabel': 'Status',
    'tracking.locationLabel': 'Location',
    'tracking.typeLabel': 'Type',
    'tracking.typeOnline': 'Online',
    'tracking.cancelledMsg': 'This order has been cancelled.',
    'tracking.progressTitle': 'Order Progress',
    'tracking.itemsTitle': 'Order Items',
    'tracking.noItemsMsg': 'No item details available.',
    'tracking.timelineTitle': 'Timeline',
    'tracking.orderPlacedTitle': 'Order placed',
    'tracking.orderPlacedDesc': 'Your order has been received.',
    'tracking.statusPending': 'Order Placed',
    'tracking.statusConfirmed': 'Confirmed',
    'tracking.statusPacked': 'Packed',
    'tracking.statusInTransit': 'In Transit',
    'tracking.statusDelivered': 'Delivered',
    'tracking.statusCancelled': 'Cancelled',
  },
  am: {
    'nav.home': 'ቤት',
    'nav.products': 'ምርቶች',
    'nav.about': 'ስለ እኛ',
    'nav.contact': 'አግኙን',
    'nav.login': 'ግባ',
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.trackOrder': 'ትዕዛዝ ተከታተል',
    'header.language': 'ቋንቋ ይምረጡ',
    'header.organic': 'ኦርጋኒክ',
    'common.welcome': 'እንኳን ደህና መጣህ',
    'common.logout': 'ውጣ',
    'common.currency': 'ብር',
    'common.submit': 'ጥያቄ ያስገቡ',
    'common.loading': 'በማስኬድ ላይ...',
    'common.sending': 'በመላክ ላይ...',

    // Hero Section
    'hero.title1': "የተፈጥሮ ንፅህና፣",
    'hero.title2': "ለእርስዎ ታሽጎ ቀርቧል።",
    'hero.subtitle': "ፕሪሚየም ኦርጋኒክ ተጨማሪዎች፣ ከኢትዮጵያ እርሻዎች በስነ-ምግባር የተገኙ እና በጥንቃቄ የሚደርሱ።",
    'hero.btn.order': "ትዕዛዝ ያስገቡ",
    'hero.btn.about': "ስለ እኛ",
    'hero.btn.bulk': "የጅምላ ትዕዛዞች",
    'hero.stat.products': "ምርቶች",
    'hero.stat.customers': "ደንበኞች",
    'hero.stat.natural': "ተፈጥሯዊ",
    'hero.stat.farms': "የሀገር ውስጥ እርሻዎች",

    'bestSellers.title': 'የተመረጡ ኦርጋኒክ',
    'bestSellers.titleHighlight': 'ማሟያዎች',
    'bestSellers.subtitle': 'ከኢትዮጵያ ተራራማ አካባቢዎች የተገኙ። እያንዳንዱ ምርት በሶስተኛ ወገን የተፈተነ እና ኦርጋኒክነቱ የተረጋገጠ ነው።',
    'bestSellers.badgeFeatured': 'የተመረጠ',
    'bestSellers.comingSoon': 'በቅርቡ ይጠብቁን',
    'bestSellers.comingSoonDesc': 'የምርት ማውጫችን እየተዘመነ ነው። በቅርቡ ተመልሰው ይጎብኙ።',
    'bestSellers.priceFrom': 'የመነሻ ዋጋ',
    'bestSellers.defaultDesc': 'ከኢትዮጵያ ተራራማ አካባቢዎች የተገኘ ከፍተኛ ጥራት ያለው ኦርጋኒክ ማሟያ።',
    'bestSellers.buyNow': 'አሁን ይግዙ',
    'bestSellers.orderAny': 'ማንኛውንም ምርት ይዘዙ',
    'dailyHighlights.shopByCategory': 'በምድብ ይገበያዩ',
    'dailyHighlights.defaultDesc': 'የዚህን ተፈጥሯዊ ምርት ንፁህ ጥቅም ያጣጥሙ። በጥንቃቄ የተሰበሰበ እና የተዘጋጀ።',
    'categories.powders': 'ዱቄቶች',
    'categories.oils': 'ዘይቶች',
    'categories.seeds': 'ዘሮች',
    'categories.supplements': 'ማሟያዎች',
    'categories.herbsSpices': 'ቅመማ ቅመሞች',
    'categories.essentialOils': 'አስፈላጊ ዘይቶች',
    'categories.naturalBeauty': 'ተፈጥሯዊ ውበት',
    'categories.wellness': 'ጤና እና ደህንነት',
    'tags.trending': 'ተወዳጅ',
    'tags.bestseller': 'በብዛት የተሸጠ',
    'tags.organic': 'ኦርጋኒክ',
    'tags.supplement': 'ማሟያ',
    'tags.pure': 'ንፁህ',
    'tags.superfood': 'ልዩ ምግብ',
    'tags.essential': 'አስፈላጊ',
    'tags.herbal': 'ዕፅዋት',
    'tags.aromatic': 'መዓዛማ',
    'tags.natural': 'ተፈጥሯዊ',
    'tags.spice': 'ቅመም',
    'carousel.subtitle': 'እኛን እየጎበኙ ይማሩ',
    'carousel.title': 'ጤናማ ማንነትዎን ይገንቡ',
    'carousel.desc': 'ስለ እውነተኛው የኢትዮጵያ ምርቶቻችን የተለያዩ ተፈጥሯዊ ጥቅሞች ለማወቅ ካርዶቹን ይጫኑ።',
    'carousel.shopNow': 'አሁን ይገበያዩ',
    'story.title': 'ከቅርስ የመነጨ፣',
    'story.titleHighlight': 'በንፅህና የሚመራ።',
    'story.desc': 'ለም በሆነው የአሰላ ሸለቆ የተመሰረተው ድርጅታችን የጀመረው በአንድ ቀላል ተልዕኮ ነው፡ የኢትዮጵያን ጥንታዊ የግብርና ጥበብ ጠብቆ ማቆየት እና አለም አቀፍ የኦርጋኒክ መስፈርቶችን ማሟላት። እውነተኛ ጤና ከምድር እንደሚመጣ እናምናለን።',
    'story.feature1Title': '100% ኦርጋኒክ',
    'story.feature1Desc': 'እያንዳንዱ ምርት ከተዋሃዱ (synthetic) ተጨማሪዎች ነፃ መሆኑ ተረጋግጧል።',
    'story.feature2Title': 'በስነ-ምግባር የተገኘ',
    'story.feature2Desc': 'ፍትሃዊ ደሞዝ እና ዘላቂ አሰራሮችን በማቅረብ ማህበረሰባችንን እንደግፋለን።',
    'story.feature3Title': 'በ ECAE እና AAFDA ጥራቱ የተረጋገጠ',
    'story.feature3Desc': 'በእያንዳንዱ ምርት ላይ የንፅህና እና ጥንካሬ ጥብቅ የላቦራቶሪ ምርመራ ይካሄዳል።',
    'story.feature4Title': 'ቅርስ እና ባህል',
    'story.feature4Desc': 'የትውልድ ግብርና እውቀትን ከዘመናዊ ሳይንስ ጋር አጣምሮ የያዘ።',
    'reviews.subtitle': 'እውነተኛ ተሞክሮዎች',
    'reviews.title': 'የማህበረሰባችን ',
    'reviews.titleHighlight': 'ድምፆች',
    'reviews.moreVideos': 'ተጨማሪ ቪዲዮዎች',
    'contact.subtitle': 'ያግኙን',
    'contact.title': 'ከቅርሳችን ጋር ',
    'contact.titleHighlight': 'ይገናኙ',
    'contact.desc': 'ማምረቻችንን ለመጎብኘት፣ ስለ ዘላቂ አሰራራችን ለመጠየቅ ወይም ከቡድናችን ጋር ስብሰባ ለማድረግ፣ ወደ ቅርሳችን ለሚያደርጉት ግንኙነት በደስታ እንቀበልዎታለን።',
    'contact.supportTitle': 'የደንበኞች ድጋፍ',
    'contact.amharicSupport': 'የአማርኛ ድጋፍ',
    'contact.oromooSupport': 'የአፋን ኦሮሞ ድጋፍ',
    'contact.storePiasaTitle': 'ፒያሳ መደብር',
    'contact.storePiasaDesc': 'አዲስ አበባ፣ ፒያሳ ጊዮርጊስ፣ ኤቴል አፓርትመንት',
    'contact.directions': 'አቅጣጫዎች',
    'contact.officeTitle': 'ዋና መስሪያ ቤት',
    'contact.officeDesc': 'ጀሞ ሚካኤል ወረዳ 03፣ አፍሪካ ህንፃ፣ አዲስ አበባ፣ ኢትዮጵያ',
    'contact.visitUs': 'ይጎብኙን',
    'contact.formTitle': 'ቀጠሮ ያስይዙ',
    'contact.formSuccess': 'ጥያቄው በተሳካ ሁኔታ ተልኳል! በቅርቡ እናገኝዎታለን።',
    'contact.formError': 'ጥያቄውን መላክ አልተቻለም። እባክዎ እንደገና ይሞክሩ።',
    'contact.fullName': 'ሙሉ ስም *',
    'contact.fullNamePlaceholder': 'ስምዎን ያስገቡ',
    'contact.phone': 'ስልክ ቁጥር *',
    'contact.phonePlaceholder': 'ስልክ ቁጥርዎን ያስገቡ',
    'contact.email': 'ኢሜል አድራሻ (አማራጭ)',
    'contact.emailPlaceholder': 'ኢሜልዎን ያስገቡ',
    'contact.date': 'የተመረጠ ቀን *',
    'footer.paymentOptions': 'የክፍያ አማራጮች',
    'footer.importantLinks': 'አስፈላጊ አገናኞች',
    'footer.home': 'መነሻ',
    'footer.catalog': 'ካታሎግ',
    'footer.ourStory': 'የእኛ ታሪክ',
    'footer.privacyPolicy': 'የግላዊነት ፖሊሲ',
    'footer.followUs': 'ይከተሉን',
    'footer.contact': 'አድራሻ',
    'footer.copyright': '© 2026 አሰላ ኦርጋኒክ። መብቱ በህግ የተጠበቀ ነው።',
    'footer.rights': '© 2026 አሰላ ኦርጋኒክ። መብቱ በህግ የተጠበቀ ነው።',
    'footer.termsOfService': 'የአገልግሎት ውሎች',
    'orderForm.titleFranchise': 'የፍራንቻይዝ አጋር ፖርታል',
    'orderForm.titleSales': 'አዲስ የሽያጭ ትዕዛዝ',
    'orderForm.titleDefault': 'ትዕዛዝዎን ያጠናቅቁ',
    'orderForm.subtitleFranchise': 'ለፍራንቻይዝ መደብሮች የጅምላ ጥያቄዎችን ያስገቡ።',
    'orderForm.subtitleSales': 'አዲስ የችርቻሮ ደንበኛ ይመዝግቡ።',
    'orderForm.ordering': 'እያዘዙ ነው: ',
    'orderForm.customerName': 'የደንበኛ / የድርጅት ስም',
    'orderForm.customerNamePlaceholder': 'ሙሉ ስም ወይም የድርጅት ስም',
    'orderForm.franchiseType': 'የፍራንቻይዝ አይነት',
    'orderForm.gender': 'ፆታ',
    'orderForm.select': 'ይምረጡ',
    'orderForm.male': 'ወንድ',
    'orderForm.female': 'ሴት',
    'orderForm.ageGroup': 'የእድሜ ክልል',
    'orderForm.source': 'ምንጭ',
    'orderForm.sourceWebsite': 'ድር ጣቢያ / በመስመር ላይ',
    'orderForm.sourcePhone': 'ስልክ',
    'orderForm.sourceWalkIn': 'በአካል መምጣት',
    'orderForm.sourceOther': 'ሌላ',
    'orderForm.orderType': 'የትዕዛዝ አይነት',
    'orderForm.delivery': 'መላኪያ',
    'orderForm.pickup': 'በአካል መውሰድ',
    'orderForm.referralCode': 'የሪፈራል ኮድ (አማራጭ)',
    'orderForm.location': 'አካባቢ',
    'orderForm.locAddis': 'አዲስ አበባ',
    'orderForm.locOther': 'ሌሎች ክልሎች',
    'orderForm.locAbroad': 'ውጭ አገር',
    'orderForm.city': 'ከተማ / የተለየ አካባቢ',
    'orderForm.phone': 'ስልክ ቁጥር',
    'orderForm.itemDetailsTitle': 'የእቃ ዝርዝሮች',
    'orderForm.itemLabel': 'እቃ',
    'orderForm.itemPlaceholder': 'እቃ ይምረጡ...',
    'orderForm.packageSize': 'የማሸጊያ መጠን',
    'orderForm.chooseItemFirst': 'ቅድሚያ እቃ ይምረጡ',
    'orderForm.qty': 'ብዛት',
    'orderForm.deliveryDate': 'የመላኪያ ቀን',
    'orderForm.addAnotherItem': '+ ሌላ እቃ ጨምር',
    'orderForm.deliveryFeeInfoTitle': 'የመላኪያ ክፍያ መረጃ:',
    'orderForm.deliveryFeeInfoText': 'አዲስ አበባ: 200 ብር | ከአዲስ አበባ ውጭ: 300 ብር | አለም አቀፍ: እንደየ ክልሉ ይለያያል',
    'orderForm.notes': 'የትዕዛዝ ማስታወሻዎች / ልዩ መመሪያዎች',
    'orderForm.attachment': 'አባሪ (ደረሰኝ / መታወቂያ)',
    'orderForm.total': 'ጠቅላላ:',
    'orderForm.successMessage': 'ትዕዛዙ በተሳካ ሁኔታ ገብቷል!',
    'orderForm.errorMessage': 'ትዕዛዙን ማስገባት አልተቻለም',
    'orderForm.errorOccurred': 'ስህተት ተከስቷል',
    'tracking.subtitle': 'ትዕዛዝ መከታተያ',
    'tracking.title': 'ትዕዛዝዎን ይከታተሉ',
    'tracking.desc': 'የጥቅልዎን የአሁናዊ ሁኔታ ዝመናዎችን ለማግኘት የትዕዛዝ መለያዎን ከዚህ በታች ያስገቡ።',
    'tracking.placeholder': 'ለምሳሌ ORD-001234',
    'tracking.searching': 'በመፈለግ ላይ...',
    'tracking.trackBtn': 'ተከታተል',
    'tracking.notFound': 'ለዚያ መለያ ምንም ትዕዛዝ አልተገኘም። የትዕዛዝ ቁጥሩን ያረጋግጡ እና እንደገና ይሞክሩ።',
    'tracking.errorMsg': 'ይህን ትዕዛዝ መከታተል አልተቻለም',
    'tracking.orderIdLabel': 'የትዕዛዝ መለያ',
    'tracking.placedOnLabel': 'የታዘዘበት ቀን',
    'tracking.customerLabel': 'ደንበኛ',
    'tracking.totalAmountLabel': 'ጠቅላላ ዋጋ',
    'tracking.statusLabel': 'ሁኔታ',
    'tracking.locationLabel': 'አካባቢ',
    'tracking.typeLabel': 'አይነት',
    'tracking.typeOnline': 'በመስመር ላይ',
    'tracking.cancelledMsg': 'ይህ ትዕዛዝ ተሰርዟል።',
    'tracking.progressTitle': 'የትዕዛዝ ሂደት',
    'tracking.itemsTitle': 'የታዘዙ እቃዎች',
    'tracking.noItemsMsg': 'ምንም የእቃ ዝርዝሮች የሉም።',
    'tracking.timelineTitle': 'የጊዜ ሰሌዳ',
    'tracking.orderPlacedTitle': 'ትዕዛዝ ገብቷል',
    'tracking.orderPlacedDesc': 'ትዕዛዝዎ ደርሶናል።',
    'tracking.statusPending': 'ትዕዛዝ ገብቷል',
    'tracking.statusConfirmed': 'ተረጋግጧል',
    'tracking.statusPacked': 'ታሽጓል',
    'tracking.statusInTransit': 'በመንገድ ላይ ነው',
    'tracking.statusDelivered': 'ደርሷል',
    'tracking.statusCancelled': 'ተሰርዟል',
  },
  or: {
    'nav.home': 'Mana',
    'nav.products': 'Oomisha',
    'nav.about': 'Waaʼee Keenya',
    'nav.contact': 'Quunnamtii',
    'nav.login': 'Seeni',
    'nav.dashboard': 'Daashboordii',
    'nav.trackOrder': 'Ajaja Hordofi',
    'header.language': 'Afaan Filadhu',
    'header.organic': 'Uumamaa',
    'common.welcome': 'Baga Nagaan Dhuftan',
    'common.logout': 'Baʼi',
    'common.currency': 'ETB',
    'common.submit': 'Gaaffii Galchi',
    'common.loading': 'Adeemsifamaa jira...',
    'common.sending': 'Ergamaa jira...',

    // Hero Section
    'hero.title1': "Qulqullina Uumamaa,",
    'hero.title2': "Isiniif Qophaa'e.",
    'hero.subtitle': "Oomishaalee uumamaa qulqullina qaban, qonnaan bultoota Itoophiyaa irraa haala gaariin kan sassaabaman.",
    'hero.btn.order': "Ajaji",
    'hero.btn.about': "Waaʼee Keenya",
    'hero.btn.bulk': "Ajaja Jumlaa",
    'hero.stat.products': "Oomishaalee",
    'hero.stat.customers': "Maamiltoota",
    'hero.stat.natural': "Uumamaa",
    'hero.stat.farms': "Qonna Naannoo",
    
    'bestSellers.title': 'Orgaanikii Filataman',
    'bestSellers.titleHighlight': 'Dabalatawwan',
    'bestSellers.subtitle': 'Gaarren Itoophiyaa irraa kan argame. Oomishni hundinuu qaama sadaffaatiin kan qoratameefi orgaanikii ta\'uun isaa kan mirkanaa\'eedha.',
    'bestSellers.badgeFeatured': 'Filatamaa',
    'bestSellers.comingSoon': 'Dhiyootti',
    'bestSellers.comingSoonDesc': 'Tarreen oomishaa keenya haaromfamaa jira. Yeroo dhiyootti deebi\'aa ilaalaa.',
    'bestSellers.priceFrom': 'Gatii Ka\'umsaa',
    'bestSellers.defaultDesc': 'Dabalata orgaanikii qulqullina olaanaa qabu kan gaarren Itoophiyaa irraa argame.',
    'bestSellers.buyNow': 'Amma Biti',
    'bestSellers.orderAny': 'Oomisha Kamiyyuu Ajaji',
    'dailyHighlights.shopByCategory': 'Ramaddiin Biti',
    'dailyHighlights.defaultDesc': 'Faayidaa uumamaa qulqulluu oomisha kanaa muuxadhu. Of eeggannoodhaan kan sassaabameefi qophaa\'e.',
    'categories.powders': 'Daakuuwwan',
    'categories.oils': 'Zayitoota',
    'categories.seeds': 'Sanyiiwwan',
    'categories.supplements': 'Dabalatawwan',
    'categories.herbsSpices': 'Qimamiiwwan',
    'categories.essentialOils': 'Zayitoota Barbaachisoo',
    'categories.naturalBeauty': 'Bareedina Uumamaa',
    'categories.wellness': 'Fayyaa',
    'tags.trending': 'Jaallatamaa',
    'tags.bestseller': 'Baay\'ee kan Gurgurame',
    'tags.organic': 'Orgaanikii',
    'tags.supplement': 'Dabalata',
    'tags.pure': 'Qulqulluu',
    'tags.superfood': 'Nyaata Addaa',
    'tags.essential': 'Barbaachisaa',
    'tags.herbal': 'Qoricha Uumamaa',
    'tags.aromatic': 'Urgaawaa',
    'tags.natural': 'Uumamaa',
    'tags.spice': 'Qimamii',
    'carousel.subtitle': 'Nu Daawwachaa Baradhaa',
    'carousel.title': 'Eenyummaa Fayyaalessa Keetii Ijaari',
    'carousel.desc': 'Faayidaawwan uumamaa adda addaa oomisha Itoophiyaa keenyaa qorachuuf kaardiiwwan cuqaasi.',
    'carousel.shopNow': 'Amma biti',
    'story.title': 'Aadaa irraa kan Madde,',
    'story.titleHighlight': 'Qulqullinaan kan Dhooggame.',
    'story.desc': 'Sulula gabbataa Asallaa keessatti kan hundeeffame, dhaabbanni keenya ergama salphaa tokkoon eegale: beekumsa qonnaa durii Itoophiyaa eeguu fi ulaagaalee orgaanikii idil-addunyaa guutuu. Fayyaan dhugaa lafa irraa, akkaataa uumamaan, akka maddu amanna.',
    'story.feature1Title': '100% Orgaanikii',
    'story.feature1Desc': 'Oomishni hundinuu wantoota namtolchee (synthetic) irraa bilisa ta\'uun isaa mirkanaa\'era.',
    'story.feature2Title': 'Naamusa Qabeessa',
    'story.feature2Desc': 'Mindaa madaalawaafi hojiiwwan itti fufiinsa qaban dhiyeessuudhaan hawaasa keenya ni deeggarra.',
    'story.feature3Title': 'Qulqullinichi ECAE fi AAFDA tiin Mirkanaa\'eera',
    'story.feature3Desc': 'Oomisha hundaaf qorannoon laaboraatorii cimaan qulqullinaafi humnaaf ni godhama.',
    'story.feature4Title': 'Aadaa fi Duudhaa',
    'story.feature4Desc': 'Beekumsa qonnaa dhalootaa saayinsii ammayyaa wajjin walitti fiduu.',
    'reviews.subtitle': 'Muuxannoowwan Dhugaa',
    'reviews.title': 'Sagalee Hawaasa ',
    'reviews.titleHighlight': 'Keenyaa',
    'reviews.moreVideos': 'Viidiyoowwan Dabalataa',
    'contact.subtitle': 'Nu Quunnamaa',
    'contact.title': 'Aadaa Keenya Waliin ',
    'contact.titleHighlight': 'Wal-quunnamaa',
    'contact.desc': 'Bakka oomishaa keenya daawwachuu, waa\'ee hojiiwwan keenya itti fufiinsa qaban gaafachuu, ykn garee keenya wajjin walga\'ii qopheessuu yoo barbaaddan, quunnamtii aadaa keenyaaf gootan gammachuudhaan simanna.',
    'contact.supportTitle': 'Deeggarsa Maamiltootaa',
    'contact.amharicSupport': 'Deeggarsa Afaan Amaaraa',
    'contact.oromooSupport': 'Deeggarsa Afaan Oromoo',
    'contact.storePiasaTitle': 'Suuqii Piyaassaa',
    'contact.storePiasaDesc': 'Finfinnee, Piyaassaa Giyoorgis, Apaartaamaa Eteel',
    'contact.directions': 'Kallattiiwwan',
    'contact.officeTitle': 'Waajjira Muummee',
    'contact.officeDesc': 'Jamo Mikaa\'el Aanaa 03, Gamoo Afrikaa, Finfinnee, Itoophiyaa',
    'contact.visitUs': 'Nu Daawwadhaa',
    'contact.formTitle': 'Beellama Qabadhaa',
    'contact.formSuccess': 'Gaaffiin milkaa\'inaan ergameera! Dhiyootti isin quunnama.',
    'contact.formError': 'Gaaffii erguun hin danda\'amne. Maaloo irra deebi\'ii yaali.',
    'contact.fullName': 'Maqaa Guutuu *',
    'contact.fullNamePlaceholder': 'Maqaa kee galchi',
    'contact.phone': 'Lakkoofsa Bilbilaa *',
    'contact.phonePlaceholder': 'Lakkoofsa bilbilaa kee galchi',
    'contact.email': 'Teessoo Imeelii (Filannoo)',
    'contact.emailPlaceholder': 'Imeelii kee galchi',
    'contact.date': 'Guyyaa Filatame *',
    'footer.paymentOptions': 'Filannoowwan Kaffaltii',
    'footer.importantLinks': 'Geessituuwwan Barbaachisoo',
    'footer.home': 'Fuula Duraa',
    'footer.catalog': 'Kaataaloogii',
    'footer.ourStory': 'Seenaa Keenya',
    'footer.privacyPolicy': 'Imaammata Mateenyaa',
    'footer.followUs': 'Nu Hordofaa',
    'footer.contact': 'Quunnamtii',
    'footer.copyright': '© 2026 Asellaa Orgaanikii. Mirgi hundinuu seeraan eeggamaadha.',
    'footer.rights': '© 2026 Asellaa Orgaanikii. Mirgi hundinuu seeraan eeggamaadha.',
    'footer.termsOfService': 'Haalawwan Tajaajilaa',
    'orderForm.titleFranchise': 'Keesummeessaa Michuu Firaanchaayizii',
    'orderForm.titleSales': 'Ajaja Gurgurtaa Haaraa',
    'orderForm.titleDefault': 'Ajaja Kee Xumuri',
    'orderForm.subtitleFranchise': 'Suuqiiwwan firaanchaayiziitiif gaaffiiwwan jimlaa galchi.',
    'orderForm.subtitleSales': 'Galmee maamila qinxaaboo haaraa hundeessi.',
    'orderForm.ordering': 'Ajajamaa jira: ',
    'orderForm.customerName': 'Maqaa Maamilaa / Dhaabbataa',
    'orderForm.customerNamePlaceholder': 'Maqaa guutuu ykn maqaa dhaabbataa',
    'orderForm.franchiseType': 'Gosa Firaanchaayizii',
    'orderForm.gender': 'Saala',
    'orderForm.select': 'Fili',
    'orderForm.male': 'Dhiira',
    'orderForm.female': 'Dubartii',
    'orderForm.ageGroup': 'Garee Umrii',
    'orderForm.source': 'Madda',
    'orderForm.sourceWebsite': 'Weebsaayitii / Toora Intarneetii',
    'orderForm.sourcePhone': 'Bilbila',
    'orderForm.sourceWalkIn': 'Qaamaan Dhufee',
    'orderForm.sourceOther': 'Kan biroo',
    'orderForm.orderType': 'Gosa Ajajaa',
    'orderForm.delivery': 'Geejjibsiisuu',
    'orderForm.pickup': 'Qaamaan Fudhachuu',
    'orderForm.referralCode': 'Koodii Rifeeraalii (Filannoo)',
    'orderForm.location': 'Bakka',
    'orderForm.locAddis': 'Finfinnee',
    'orderForm.locOther': 'Naannoolee Biroo',
    'orderForm.locAbroad': 'Biyya Alaatti',
    'orderForm.city': 'Magaalaa / Naannoo Addaa',
    'orderForm.phone': 'Lakkoofsa Bilbilaa',
    'orderForm.itemDetailsTitle': 'Ibsa Meeshaa',
    'orderForm.itemLabel': 'Meeshaa',
    'orderForm.itemPlaceholder': 'Meeshaa fili...',
    'orderForm.packageSize': 'Hamma Saamsamaa',
    'orderForm.chooseItemFirst': 'Dursa meeshaa fili',
    'orderForm.qty': 'Baay\'ina',
    'orderForm.deliveryDate': 'Guyyaa Geejjibsiisaa',
    'orderForm.addAnotherItem': '+ Meeshaa Biroo Ida\'i',
    'orderForm.deliveryFeeInfoTitle': 'Odeeffannoo Kaffaltii Geejjibaa:',
    'orderForm.deliveryFeeInfoText': 'Finfinnee: 200 ETB | Finfinneen Ala: 300 ETB | Idil-addunyaa: Naannoo irratti hundaa\'a',
    'orderForm.notes': 'Yaada Ajajaa / Qajeelfamoota Addaa',
    'orderForm.attachment': 'Maxxansituu (Nagahee / Waraqaa Eenyummaa)',
    'orderForm.total': 'Ida\'ama:',
    'orderForm.successMessage': 'Ajajni milkaa\'inaan ergameera!',
    'orderForm.errorMessage': 'Ajaja erguun hin danda\'amne',
    'orderForm.errorOccurred': 'Dogoggorri uumameera',
    'tracking.subtitle': 'Hordoffii Ajajaa',
    'tracking.title': 'Ajaja Kee Hordofi',
    'tracking.desc': 'Haala paakeejii keetii yeroo dhugaa keessatti hordofuuf Eenyummeessaa Ajajaa kee armaan gaditti galchi.',
    'tracking.placeholder': 'Fkn. ORD-001234',
    'tracking.searching': 'Barbaadamaa jira...',
    'tracking.trackBtn': 'Hordofi',
    'tracking.notFound': 'Eenyummeessaa sanaan ajajni hin argamne. Lakkoofsa ajajaa mirkaneessiitii irra deebi\'ii yaali.',
    'tracking.errorMsg': 'Ajaja kana hordofuun hin danda\'amne',
    'tracking.orderIdLabel': 'Eenyummeessaa Ajajaa',
    'tracking.placedOnLabel': 'Guyyaa Ajajame',
    'tracking.customerLabel': 'Maamila',
    'tracking.totalAmountLabel': 'Ida\'ama Gatii',
    'tracking.statusLabel': 'Haala',
    'tracking.locationLabel': 'Bakka',
    'tracking.typeLabel': 'Gosa',
    'tracking.typeOnline': 'Toora Intarneetiitiin',
    'tracking.cancelledMsg': 'Ajajni kun haqameera.',
    'tracking.progressTitle': 'Adeemsa Ajajaa',
    'tracking.itemsTitle': 'Meeshaalee Ajajaman',
    'tracking.noItemsMsg': 'Ibsi meeshaa hin jiru.',
    'tracking.timelineTitle': 'Yeroo Gabatee',
    'tracking.orderPlacedTitle': 'Ajajni galera',
    'tracking.orderPlacedDesc': 'Ajajni kee nu dhaqqabeera.',
    'tracking.statusPending': 'Ajajameera',
    'tracking.statusConfirmed': 'Mirkanaa\'eera',
    'tracking.statusPacked': 'Saamsameera',
    'tracking.statusInTransit': 'Geejjibamaa Jira',
    'tracking.statusDelivered': 'Dhaqqabeera',
    'tracking.statusCancelled': 'Haqameera',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage') as Language | null;
    if (savedLanguage && ['en', 'am', 'or'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
      document.documentElement.lang = savedLanguage;
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('selectedLanguage', lang);
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
